### ISSUE TITLE
AM should not be possible above  136MHz

### ISSUE THREAD

**Issue by pawol** [Tunas1337/UV-K5-Modded-Firmwares#10]
AM is not used above airband - 136MHz. So should be not available for higher frequencies.

**Comment by Tunas1337** [comment]
I've had correspondence from people that wanted AM on 350MHz, for aerial acrobatics teams.

**Comment by streamofstars** [comment]
Of course AM is used above 136MHz, there is military airband 225.0 - 399.95 MHz and they often use clear text AM.

**Comment by Tunas1337** [comment]
Duplicate of #11. Or, #11 is a duplicate of this and this is getting closed for the same reason.
