### ISSUE TITLE
[Question/Enhancement] Improving 6M Power Output

### ISSUE THREAD

**Issue by MLGHerobrine** [Tunas1337/UV-K5-Modded-Firmwares#16]
I'm a newly licensed ham radio operator, and I was looking at getting one of these radios. First off, thank you for all the work you have done on this repo. I'm excited that I can get decent airband RX for such a cheap price. Secondly, I wanted to ask whether it might be possible to improve performance on the 6m (or other) band. In the README, it shows the transmission power of "unsupported" bands being very low. I assume there is a hardware limitation that prevents a good transmit power on these frequencies, but would it be possible to improve the power here? I think it would be nice to have a cheap handheld radio that can transmit on 6m with the propagation properties of HF.

**Comment by Tunas1337** [comment]
That'd be in the realm of hardware at that point.

For obvious reasons, the RF circuitry of the UV-K5 is not tuned to receive or transmit outside of the range that the manufacturer claims, i.e. 50-600MHz. In preliminary tests, anything below 100MHz is unusably low-power and emits harmonics orders of magnitude stronger than the original signal, and to change this, you'd need to modify the filters and possibly even parts of the final stage.

**Comment by Tunas1337** [comment]
In short, it might be possible to transmit with usable amounts of power on 6m with a hardware modification and proper antenna.

**Comment by MLGHerobrine** [comment]
Okay, thank you!
