### ISSUE TITLE
Smaller Step Size

### ISSUE THREAD

**Issue by EdReardon** [Tunas1337/UV-K5-Modded-Firmwares#20]
Is it possible to reduce the step size any more?  I'm trying to scan UK CB40 (27.60125, 27.61125.... etc) but I can't directly enter or scan as these seem to fit outside of all steps?

Is this possible with firmware changes?

**Comment by Tunas1337** [comment]
Yes. Look at https://github.com/amnemonic/Quansheng_UV-K5_Firmware/blob/main/uvmod_kitchen/mod_custom_steps.py

**Comment by tilmaen** [comment]
How can I implement this? Is this already part of the nodded firmware? Can I upload just this modification?

Greetings?

**Comment by Tunas1337** [comment]
uvmod_kitchen is a tool that allows you to make your own modified firmwares with only what you want.
Look at the README file at https://github.com/amnemonic/Quansheng_UV-K5_Firmware/tree/main/uvmod_kitchen

**Comment by RE3CON** [comment]
Is it possible to provide some compiled binaries with this frequ. steps added and more microfon gain levels?

**Comment by Tunas1337** [comment]
Closing this issue since a firmware with smaller steps has been provided.
