### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by gabizro** [Tunas1337/UV-K5-Modded-Firmwares#22]
ugly painted some RX path and switch.
![UGLY_RX](https://github.com/Tunas1337/UV-K5-Modded-Firmwares/assets/7538325/58192ffe-2fe8-4abf-b09f-f37c45e2a4e9)

**Comment by Tunas1337** [comment]
Hi! If you don't mind, I'll close this since it isn't exactly an issue. It'll remain in the Closed Issues, but I'd prefer if you could repost it to the [Discussions](https://github.com/Tunas1337/UV-K5-Modded-Firmwares/discussions) board instead?
