### ISSUE TITLE
[Question] Harmonics on 6m Band

### ISSUE THREAD

**Issue by MLGHerobrine** [Tunas1337/UV-K5-Modded-Firmwares#27]
I apologize for asking this question here, but I do not have access to Telegram (maybe another platform would allow more people to join?). What are the harmonics like on the 6m band with this radio? I don't have a dummy load or reader and I don't want to interfere with anyone.

Edit: What are the harmonics + power output?

**Comment by MLGHerobrine** [comment]
Found a video with power output... I recommend putting this on the README in case anyone wonders what frequency they can transmit on without (a lot of) harmonics.
https://www.youtube.com/watch?v=ydf4jsZpaPw

**Comment by Tunas1337** [comment]
You're right, not everyone has access to Telegram. Considering the research nature of the repo, I will endeavor to compile people's test results elsehow.
For your reference, I'll put some results collected by Ismo, OH2FTG below.
![image](https://github.com/Tunas1337/UV-K5-Modded-Firmwares/assets/12097904/f12d797c-700d-47d6-a084-8f2e44b0aeec)
![image](https://github.com/Tunas1337/UV-K5-Modded-Firmwares/assets/12097904/2169105f-b419-4e3f-8459-eb5890618668)
![image](https://github.com/Tunas1337/UV-K5-Modded-Firmwares/assets/12097904/a5a4339d-3e78-4ff9-b283-9892bf738e5c)
![image](https://github.com/Tunas1337/UV-K5-Modded-Firmwares/assets/12097904/c6862be5-69db-4ed1-a3fc-4b2fa8cedcb2)
![image](https://github.com/Tunas1337/UV-K5-Modded-Firmwares/assets/12097904/ae0404dc-a807-468a-b2ef-3e71965d43c1)
![image](https://github.com/Tunas1337/UV-K5-Modded-Firmwares/assets/12097904/4ea99e96-05e8-4521-84aa-7b47aadae42e)
![image](https://github.com/Tunas1337/UV-K5-Modded-Firmwares/assets/12097904/36360c11-3782-4aec-b79d-b2488211fa67)

**Comment by MLGHerobrine** [comment]
Thanks! I'll eventually figure out how to tune the hardware to transmit on those lower frequencies. HF handhelds probably aren't practical, but they will be quite fun :)

**Comment by marusc1** [comment]
Strong harmonics also from 200to 300MHz
