### ISSUE TITLE
[Question / Suggestion] Is AM software or hardware encoded?

### ISSUE THREAD

**Issue by MLGHerobrine** [Tunas1337/UV-K5-Modded-Firmwares#29]
I don't know whether AM is software or hardware encoded. If you can transmit AM decently, would it be possible to program a single side band mod?

Another question: would it be possible to program more modes? (i.e. SSB, digital)

**Comment by Tunas1337** [comment]
- AM is software decoded, the chip is FM-only;
- there is no way to transmit AM;
- consequently, until we figure out how they're doing AM demodulation, we can't do SSB demodulation.

**Comment by marusc1** [comment]
As a help measure you can add cw wave from a signal generator,  from VNA for example to the receiving signal. Tested.
