### ISSUE TITLE
How to program frequencies that are off the radio scale?

### ISSUE THREAD

**Issue by piosylant** [Tunas1337/UV-K5-Modded-Firmwares#30]
As per the topic. The program from Quansheng does not allow to enter values other than the factory. Is there any option to save CB channels in a file and save them for use?

**Comment by Tunas1337** [comment]
Use CHIRP, with the new driver.
https://chirp.danplanet.com/issues/10478

**Comment by marusc1** [comment]
And off course by hand on the radio. Channels on 27 and 1300 can be saved. Type 0 before 27 or 70 MHz. Getting to 1280 can only be done by hitting up hundreds times from 999. 500k step helps.

**Comment by piosylant** [comment]
> Use CHIRP, with the new driver. https://chirp.danplanet.com/issues/10478

Thanks. Works.
