### ISSUE TITLE
Range outside 18 and1300?

### ISSUE THREAD

**Issue by marusc1** [Tunas1337/UV-K5-Modded-Firmwares#36]
Just for evaluation. I would like to test the physical limits. Can frequency down of 18 MHz and over 1300 MHz be set in the firmware to test the physical hardware limits?

**Comment by marusc1** [comment]
I have tried setting this using mods fro uvmod kitchen. But after using kitchen tx range stays limited to 50 to 600. Am I doing something wrong?

**Comment by Tunas1337** [comment]
Read the .md files next to each firmware; they describe the changes that have been made, why they have been made and how they affect the firmware.

**Comment by marusc1** [comment]
Thanks for the answer. I have already done what I wanted with current mvdkitchen files. The real working range is 15,750 to 1331 MHz.
