### ISSUE TITLE
Hello UV-K6 Firmware k5_v3.00.10 unable to update

### ISSUE THREAD

**Issue by madd7277727** [Tunas1337/UV-K5-Modded-Firmwares#40]
Any chance of an update to use it?

**Comment by Tunas1337** [comment]
If you have a UV-K6 with a v3 firmware and you want to use these firmwares, then try to unpack the firmware using [qsfirm.py](https://github.com/amnemonic/Quansheng_UV-K5_Firmware/blob/main/uvmod_kitchen/qsfirm.py), change the .ver.bin file to say 3.01.26, then repack it using the same tool, and flash it.

**Comment by madd7277727** [comment]
https://github.com/amnemonic/Quansheng_UV-K5_Firmware/blob/main/firmware/k5_v3.00.10_flashable.bin
https://github.com/amnemonic/Quansheng_UV-K5_Firmware/blob/main/firmware/raws/k5_v3.00.10_(uvk6_0x1FFFF).bin
Is there a difference between the two?

**Comment by Tunas1337** [comment]
> Is there a difference between the two?
Yes. If you flash the one that doesn't say "flashable", you'll brick your radio.

> There is a k5_v2.01.26_publish.bin file in it, is it necessary to execute build.bat after renaming, and change the Ver.bin in the temp folder to k5_v3.00.10?
Just run qsfirm.py manually using the same syntax as the build.bat file contains, and between unpacking and repacking, modify the ver.bin file in temp/.

**Comment by Tunas1337** [comment]
What is the error message?

**Comment by madd7277727** [comment]
The firmware version does not match, the firmware length is incorrect, this is the wrong firmware.

**Comment by Tunas1337** [comment]
There is a backup of the firmware on your radio already (it is the "flashable" bin file you mentioned before) but it has been modified to report its version as 2.01.26, so you'd need to modify it back to flash it onto your radio. I can try to do this for you if something breaks.

**Comment by madd7277727** [comment]
Please try k5_v3.00.10 to become flashable firmware, please try it.

**Comment by Tunas1337** [comment]
[k5_v3.00.10_correct-version-number.zip](https://github.com/Tunas1337/UV-K5-Modded-Firmwares/files/12012049/k5_v3.00.10_correct-version-number.zip)

**Comment by madd7277727** [comment]
This version can be updated and expanded to 18-1300. Do I need to use this? After the update, I can’t get it after clicking it?

**Comment by madd7277727** [comment]
Hard work, use https://github.com/Tunas1337/UV-K5-Modded-Firmwares/blob/main/k5_V3.00.10_encrypted_18to1300MHz.bin
It still doesn't match.
![361069763_674947211334985_5013427847774532618_n](https://github.com/Tunas1337/UV-K5-Modded-Firmwares/assets/139119306/dce1d465-c8c4-47bc-8be0-d266ab684b50)

**Comment by troilus** [comment]
> 
> 
> Hard work, use https://github.com/Tunas1337/UV-K5-Modded-Firmwares/blob/main/k5_V3.00.10_encrypted_18to1300MHz.bin
> 
> It still doesn't match.
> 
> ![361069763_674947211334985_5013427847774532618_n](https://github.com/Tunas1337/UV-K5-Modded-Firmwares/assets/139119306/dce1d465-c8c4-47bc-8be0-d266ab684b50)
> 
> 

@madd7277727 Are you using UK-K6？

**Comment by madd7277727** [comment]
> > 辛苦了，使用https://github.com/Tunas1337/UV-K5-Modded-Firmwares/blob/main/k5_V3.00.10_encrypted_18to1300MHz.bin
> > 它仍然不匹配。
> > ![361069763_674947211334985_5013427847774532618_n](https://user-images.githubusercontent.com/139119306/253719838-dce1d465-c8c4-47bc-8be0-d266ab684b50.png)
> 
> @madd7277727你用的是UK-K6嗎？這個固件版本號從2到3不正確，所以也許k5可以使用，但k6不能使用。


Hello,3.00.10 is the firmware of K6, before 26 is K5.

**Comment by troilus** [comment]
> > > 辛苦了，使用https://github.com/Tunas1337/UV-K5-Modded-Firmwares/blob/main/k5_V3.00.10_encrypted_18to1300MHz.bin
> > > 它仍然不匹配。
> > > ![361069763_674947211334985_5013427847774532618_n](https://user-images.githubusercontent.com/139119306/253719838-dce1d465-c8c4-47bc-8be0-d266ab684b50.png)
> > 
> > 
> > @madd7277727你用的是UK-K6嗎？這個固件版本號從2到3不正確，所以也許k5可以使用，但k6不能使用。
> 
> Hello,3.00.10 is the firmware of K6, before 26 is K5.

The K5v3 is packed with version 26, this one is packed with version 3.00.10, it should be able to work on UV-K6. I don't have a K6 so I can't help to test.

[k6v3_18to3000.bin.zip](https://github.com/Tunas1337/UV-K5-Modded-Firmwares/files/12060991/k6v3_18to3000.bin.zip)

**Comment by Tunas1337** [comment]
A correct version has been uploaded so I'll close this issue.

**Comment by madd7277727** [comment]
> 正確的版本已上傳，因此我將關閉此問題。



> 正確的版本已上傳，因此我將關閉此問題。

Goodjob
![1689416863115 - 複製](https://github.com/Tunas1337/UV-K5-Modded-Firmwares/assets/139119306/276e6e3a-9128-4f49-94bd-9509e3f780c5)

**Comment by madd7277727** [comment]
> > > > 辛苦了，使用https://github.com/Tunas1337/UV-K5-Modded-Firmwares/blob/main/k5_V3.00.10_encrypted_18to1300MHz.bin
> > > > 仍然不匹配。
> > > > ![361069763_674947211334985_5013427847774532618_n](https://user-images.githubusercontent.com/139119306/253719838-dce1d465-c8c4-47bc-8be0-d266ab684b50.png)
> > > 
> > > 
> > > @madd7277727你用的是UK-K6嗎？這個固件版本號從2到3不正確，所以也許k5可以使用，但k6不能使用。
> > 
> > 
> > 您好，3.00.10是K6的固件，26之前是K5的固件。
> 
> K5v3 打包的是版本 26，這個打包的是版本 3.00.10，它應該能夠在 UV-K6 上工作。我沒有K6所以無法幫助測試。
> 
> [k6v3_18to3000.bin.zip](https://github.com/Tunas1337/UV-K5-Modded-Firmwares/files/12060991/k6v3_18to3000.bin.zip)

IS OK , thank you very much.
