### ISSUE TITLE
Cannot update firmware k5_26_encrypted_18to1300Mhz_500k_step on UV-K5

### ISSUE THREAD

**Issue by YD9CKH** [Tunas1337/UV-K5-Modded-Firmwares#51]
cannot update to firmware k5_26_encrypted_18to1300Mhz_500k_step.bin, erros is the length of the file is to much!.

Would you like to show me how to fixes?
Thank u

**Comment by Tunas1337** [comment]
Open the file in Notepad. You will see that it is not the firmware file, but instead the HTML code of the GitHub page.
Don't right-click and press "Save As." Open the page with the file and use the download button:
![image](https://github.com/Tunas1337/UV-K5-Modded-Firmwares/assets/12097904/468852f0-3e2b-403a-8246-9dbd23878d86)
