### ISSUE TITLE
Upper max frequency should be limited to 629.99000 MHz. Remainig 840-850 is useless

### ISSUE THREAD

**Issue by pawol** [Tunas1337/UV-K5-Modded-Firmwares#9]
Upper max frequency should be limited to 629.99000 MHz.
I have checked on spectrum analyser and maximum frequency transmitted by K5 is 629.9900MHz.
No common sense to allow higher frequencies above 629,9900MHz

**Comment by pawol** [comment]
I have checked on spectrum analyser and the range 50,0000-629,9900 MHz i transmitted by K5.
firmware used:  k5_v2.01.19_mod_TX_50to850mhz

**Comment by Tunas1337** [comment]
Hi,

You're right - there is a gap in the capabilities of the Beken BK4819 chip: _"The Quansheng UV-K5 CAN NOT receive signals between 630-840MHz. This is a hardware limitation of the Beken BK4819 baseband chip."_
The actual range is 18-630MHz, 840-1300MHz (or so the datasheet says.)

**Comment by pawol** [comment]
Sure, but I was able to set higher frequencies on K5 than 629,990. Transmitted signal above narrow range 840-850 is very weak and useless so there is no sense to leave it unlimited

**Comment by fagci** [comment]
It can be helpful to test another devices to receive at higher frequencies. So, I think, issues not for add restrictions. Need to make customizer tool then.

**Comment by pawol** [comment]
What do you want to receive on 840MHz. LTE? There is nothing interesting to receive there. When freq is set 630-840 and nothing is received  we make too more mess

**Comment by Yag00000** [comment]
I think that from 1080mhz to 1300 it would be the best usable part for reception !!!

**Comment by pawol** [comment]
I think so high frequencies are not supported by power amplifier and input amplifier. Did anyone received eg. 27MHz CB chat from longer distance than 1 m?

**Comment by gabizro** [comment]
Indeed tested on CB with Midland 42 
Near seems like is working but at 1 meter distance almost no signal.
Also looking at photos on twitter and photos on @amnemonic seems like there are different PCB versions at least on RX path

**Comment by pawol** [comment]
So there is no common sense to allow fictious 27MHz reception  and everything below 50MHz

**Comment by Tunas1337** [comment]
> So there is no common sense to allow fictious 27MHz reception and everything below 50MHz

Then don't use that firmware. I don't know what else to tell you.
I had specific requests from people to make 27MHz RX possible, and those same people sent me videos of it working and receiving CB chatter from distant stations. They did, however, use a proper antenna.
Transmission, on the other hand, is a different beast entirely. We're still examining the effectiveness of it, and whether any 
reasonably small hardware modifications to the output stage could improve its effectiveness in certain areas. I would only recommend the experimental transmission enabling firmware for those who have a dummy load, a spectrum analyzer or similar equipment and time on their hands. I would not recommend it for those that want to accomplish any communication purpose, especially with the low output power.

I am closing this issue as "not planned", as the presence of options that work within a limited capacity is better than no option at all.

**Comment by marusc1** [comment]
The antenna delivered with the radio is vhf/uhf antenna. It incorporates a short circuit for lower frequencies. This is why reception is not possible. Use a different antenna or a piece of wire. For CB the best wire length will be 2,68 m.
